export const horrorMovies = [
    {
        title: "The Conjuring",
        img: "/conjuring.jpeg",
        youtubeId: "k10ETZ41q5o",
        desc: "Witness the chilling true story that started it all.",
    },
    {
        title: "Annabelle",
        img: "/anabelle.jpg",
        youtubeId: "paFgQNPGlsg",
        desc: "A possessed doll unleashes terror beyond imagination.",
    },
    {
        title: "The Nun",
        img: "/nuning.jpg",
        youtubeId: "pzD9zGcUNrw",
        desc: "Evil rises in the form of a demonic nun.",
    },
    {
        title: "The Conjuring",
        img: "/conjuring.jpeg",
        youtubeId: "k10ETZ41q5o",
        desc: "Witness the chilling true story that started it all.",
    },
    {
        title: "Annabelle",
        img: "/anabelle.jpg",
        youtubeId: "paFgQNPGlsg",
        desc: "A possessed doll unleashes terror beyond imagination.",
    },
    {
        title: "The Nun",
        img: "/nuning.jpg",
        youtubeId: "pzD9zGcUNrw",
        desc: "Evil rises in the form of a demonic nun.",
    },
    {
        title: "The Conjuring",
        img: "/conjuring.jpeg",
        youtubeId: "k10ETZ41q5o",
        desc: "Witness the chilling true story that started it all.",
    },
    {
        title: "Annabelle",
        img: "/anabelle.jpg",
        youtubeId: "paFgQNPGlsg",
        desc: "A possessed doll unleashes terror beyond imagination.",
    },
    {
        title: "The Nun",
        img: "/nuning.jpg",
        youtubeId: "pzD9zGcUNrw",
        desc: "Evil rises in the form of a demonic nun.",
    },
    {
        title: "The Conjuring",
        img: "/conjuring.jpeg",
        youtubeId: "k10ETZ41q5o",
        desc: "Witness the chilling true story that started it all.",
    },
    {
        title: "Annabelle",
        img: "/anabelle.jpg",
        youtubeId: "paFgQNPGlsg",
        desc: "A possessed doll unleashes terror beyond imagination.",
    },
    {
        title: "The Nun",
        img: "/nuning.jpg",
        youtubeId: "pzD9zGcUNrw",
        desc: "Evil rises in the form of a demonic nun.",
    },
    {
        title: "The Conjuring",
        img: "/conjuring.jpeg",
        youtubeId: "k10ETZ41q5o",
        desc: "Witness the chilling true story that started it all.",
    },
    {
        title: "Annabelle",
        img: "/anabelle.jpg",
        youtubeId: "paFgQNPGlsg",
        desc: "A possessed doll unleashes terror beyond imagination.",
    },
    {
        title: "The Nun",
        img: "/nuning.jpg",
        youtubeId: "pzD9zGcUNrw",
        desc: "Evil rises in the form of a demonic nun.",
    },
]
